import { PDFDocument } from "pdf-lib";
import { renderHtmlToPdfDetailed } from "../src/index";

const rows = Array.from({ length: 34 }, (_, index) => `
  <tr>
    <td class="param" rowspan="${index % 8 === 0 ? 2 : 1}">Group ${index + 1}</td>
    <td colspan="${index % 5 === 0 ? 2 : 1}">Value ${index + 1}</td>
    ${index % 5 === 0 ? "" : `<td class="diff">${index * 2}</td>`}
    <td>${index % 2 === 0 ? "Included" : "Optional"}</td>
  </tr>
  ${index % 8 === 0 ? `<tr><td>Continuation</td><td>${index + 10}</td><td>24/7</td></tr>` : ""}
`).join("");

const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    h1 { font-size: 20px; margin-bottom: 10px; }
    p { font-size: 10px; color: #4b5563; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; border: 1px solid #9aa4b2; }
    th, td { border: 1px solid #ccd3dc; padding: 6px 8px; }
    thead th { background-color: #edf2f7; text-align: center; }
    td.param { background-color: #f4f6f8; font-weight: 700; }
    td.diff { background-color: #fff1bf; text-align: right; }
  </style>
</head>
<body>
  <h1>CSS Table Report</h1>
  <p>Checks table border, padding, border-collapse, colspan, rowspan, repeated headers, footer, and page numbers.</p>
  <table>
    <thead>
      <tr><th>Metric</th><th>Primary</th><th>Delta</th><th>Status</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`;

async function writeExamplePdf(filename: string, pdf: Uint8Array): Promise<string> {
  const target = new URL(filename, import.meta.url);
  try {
    await Bun.write(target, pdf);
    return target.pathname;
  } catch (error) {
    if (!(error instanceof Error) || !error.message.includes("EBUSY")) throw error;
    const fallback = new URL(filename.replace(/\.pdf$/i, `-${Date.now()}.pdf`), import.meta.url);
    await Bun.write(fallback, pdf);
    return fallback.pathname;
  }
}

const result = await renderHtmlToPdfDetailed({
  html,
  repeatHeaders: true,
  watermarkText: "DRAFT",
  watermarkOpacity: 8,
  pageHeader: { text: "CSS Table Report", align: "right" },
  pageFooter: { text: "Generated by Html2PdfSmith", align: "left" },
  pageNumbers: { format: "Page {page}", align: "right" },
});

const output = await writeExamplePdf("./css-table.pdf", result.pdf);
const loaded = await PDFDocument.load(result.pdf);
console.log({
  output,
  pages: result.pages,
  actualPages: loaded.getPageCount(),
  bytes: result.pdf.byteLength,
  warnings: result.warnings,
});
