import { renderHtmlToPdfDetailed } from "../src/index";

async function writeExamplePdf(filename: string, pdf: Uint8Array): Promise<string> {
  const target = new URL(filename, import.meta.url);
  try {
    await Bun.write(target, pdf);
    return target.pathname;
  } catch (error) {
    if (!(error instanceof Error) || !error.message.includes("EBUSY")) throw error;
    const fallback = new URL(filename.replace(/\.pdf$/i, `-${Date.now()}.pdf`), import.meta.url);
    await Bun.write(fallback, pdf);
    return fallback.pathname;
  }
}

const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    table {
      width: 100%;
      border-collapse: collapse;
      border: 1px solid #b7c0cb;
    }
    th, td {
      border: 1px solid #d7dce3;
      padding: 7px 9px;
    }
    thead th {
      background-color: #f0f4f8;
      text-align: center;
    }
    td.param-name {
      background-color: #f4f6f8;
      font-weight: 700;
    }
    td.diff {
      background-color: #fff1bf;
    }
  </style>
</head>
<body>
  <header class="header">
    <div class="brand-name">ACME REPORTS</div>
  </header>
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th class="param-name">Metric</th>
          <th data-column-id="a">Plan A Premium</th>
          <th data-column-id="b">Plan B Business</th>
          <th data-column-id="c">Plan C Enterprise</th>
        </tr>
        <tr>
          <th class="param-name"></th>
          <th class="price" data-column-id="a">$199</th>
          <th class="price" data-column-id="b">$349</th>
          <th class="price" data-column-id="c">$799</th>
        </tr>
      </thead>
      <tbody>
        <tr class="section-title"><td colspan="4" class="section-header">General</td></tr>
        <tr><td class="param-name">Users</td><td>10</td><td class="diff">50</td><td class="diff">Unlimited</td></tr>
        <tr><td class="param-name">Storage</td><td>100 GB</td><td>1 TB</td><td>10 TB</td></tr>
        <tr><td class="param-name" rowspan="2">Support</td><td colspan="2">Email and chat</td><td>Dedicated manager</td></tr>
        <tr><td>Business hours</td><td>24/7</td><td>24/7 priority</td></tr>
        <tr class="section-title"><td colspan="4" class="section-header">International Text</td></tr>
        <tr><td class="param-name">中文参数</td><td>支持</td><td>支持</td><td>支持</td></tr>
        <tr><td class="param-name">Кириллица</td><td>Да</td><td>Да</td><td>Да</td></tr>
      </tbody>
    </table>
  </div>
</body>
</html>`;

const result = await renderHtmlToPdfDetailed({
  html,
  repeatHeaders: true,
  watermarkText: "CONFIDENTIAL",
  watermarkScale: 45,
  watermarkOpacity: 18,
  pageHeader: { text: "ACME Reports - confidential comparison", align: "right" },
  pageFooter: { text: "Generated by Html2PdfSmith", align: "left" },
  pageNumbers: { format: "Page {page}", align: "right" },
  font: { autoDiscover: true },
});

const output = await writeExamplePdf("./simple-table.pdf", result.pdf);
console.log({
  output,
  pages: result.pages,
  columns: result.columns,
  orientation: result.orientation,
  warnings: result.warnings,
});
